# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0006_auto_20170414_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('age', models.DateTimeField(default='2000-10-01', verbose_name='date of birth')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_project.Owner')),
            ],
        ),
    ]
