# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0007_horse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='age',
        ),
    ]
