# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0008_auto_20170414_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='age',
            field=models.DateTimeField(default='2000-10-01', verbose_name='date of birth'),
        ),
    ]
