# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0009_horse_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='farrier',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Farrier'),
        ),
        migrations.AddField(
            model_name='horse',
            name='grain',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Grain'),
        ),
        migrations.AlterField(
            model_name='student',
            name='trainer',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Trainer'),
        ),
    ]
