# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0011_auto_20170418_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='age',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
