# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0012_auto_20170418_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=300)),
                ('country_of_origin', models.CharField(default='United States', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='grain',
            name='brand',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Brand'),
        ),
    ]
