# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0013_auto_20170419_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='farrierCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_purpose', models.CharField(choices=[('TR', 'Trim'), ('FS', 'Front shoes'), ('BS', 'Back shoes'), ('AS', 'All four shoes'), ('Alum', 'Aluminum shoes'), ('Steel', 'Steel shoes'), ('Spec', 'Specialty shoes')], max_length=2)),
                ('notes', models.CharField(blank='True', max_length=1000)),
                ('farrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_project.Farrier')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarycare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_purpose', models.CharField(choices=[('RT', 'Routine'), ('NC', 'New Complaint'), ('FL', 'Followup'), ('PP', 'Prepurchase')], max_length=1)),
                ('notes', models.CharField(blank='True', max_length=1000)),
                ('attachments', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.uploadFile')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_project.Veterinarian')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='farrier_care',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.farrierCare'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='vet_care',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Veterinarycare'),
        ),
    ]
