# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0018_auto_20170430_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarian',
            name='email',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='phone_number',
        ),
    ]
