# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0021_auto_20170509_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarycare',
            name='date',
        ),
    ]
