# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0022_remove_veterinarycare_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='farrier_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_project.farrierCare'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='vet_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_project.Veterinarycare'),
        ),
    ]
