# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0024_auto_20170509_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOP', max_length=300)),
                ('phone_number', models.CharField(blank=True, default='8008888888', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank='True', max_length=700)),
                ('email', models.EmailField(blank='True', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='email',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='vet_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_project.veterinaryCare'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Person'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='clinick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_project.Clinic'),
        ),
    ]
