# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_project', '0025_auto_20170623_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=6, null='True')),
                ('owing', models.DecimalField(decimal_places=2, max_digits=6, null='True')),
                ('description', models.CharField(max_length=50, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_primary', models.CharField(blank='True', max_length=100)),
                ('allergy_secondary', models.CharField(blank='True', max_length=100)),
                ('allergy_tertiary', models.CharField(blank='True', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensation', models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('CR', 'credit')], max_length=2)),
                ('arrived', models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('L', 'late')], max_length=2)),
                ('horse', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Horse')),
                ('name', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Person')),
                ('trainer', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Trainer')),
                ('training_plans', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='studentCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank='False', editable='True')),
                ('lesson', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Lesson')),
                ('student', models.ForeignKey(blank='False', null='False', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='farrier_care',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='vet_care',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='days_ordered',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='ordered_on',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='clinick',
        ),
        migrations.AddField(
            model_name='breed',
            name='breed_primary',
            field=models.CharField(blank='True', max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='breed_secondary',
            field=models.CharField(blank='True', max_length=100),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='horse',
            name='allergies',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Allergies'),
        ),
        migrations.AddField(
            model_name='person',
            name='account',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='pet_project.Account'),
        ),
    ]
